name: build push image for deployment
on:
  push:
    branches:
      - main

jobs:
  build-section:
    environment: action
    runs-on: ubuntu-latest

    steps:
      - name: print something
        run: echo "Here Modulithers!! i am printing something"
      - name: show host environment variable
        run: echo "actuator endpoint  ${{ACTUATOR_EXPOSED_ENDPOINTS}}"

#  push-image-section