name: build push image for deployment
on:
  push:
    branches:
      - main

env:
  job_env: sssss

jobs:
  sample-job-section:
    environment: action
    runs-on: ubuntu-latest
    env:
      SOME_ENV: some_Data

    steps:
      - name: print something
        run: echo "Here Modulithers!! i am printing something"
      - name: show host environment variable
        run: echo "some data ${{ env.SOME_ENV }}  actuator endpoint  ${{ vars.ACTUATOR_EXPOSED_ENDPOINTS }}"
      - name: print job
        env:
          step_level_env: stepenv
        run: echo " job env ${{ env.job_env }}   step env ${{ env.step_level_env }}"


  build-job-section:
    environment: action
    runs-on: ubuntu-latest

    container: postgres
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: ${{ vars.MODULITH_DB_NAME }}
          POSTGRES_PASSWORD: ${{ secrets.MODULITH_PASSWORD }}
          POSTGRES_USER: ${{ secrets.MODULITH_USERNAME }}
        ports:
          - 5432:5432

    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Set Up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: maven

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2
      - name: Output Info
        run: ls && mvn -version && ls /opt

      - name: Build with maven
        run: mvn clean package -DskipTests -Dspring-boot.run.profiles=${{ vars.SPRING_PROFILE }}
      - name: list files
        run: ls target/**

  push-image-section:
    runs-on: ubuntu-latest
    steps:
      - name: print something
        run: echo " job env ${{ env.job_env }}"